'use client';

import Head from 'next/head';
import React from 'react';

const Dashboard = () => {
  return (
    <>
      {' '}
      <Head>
        <title>Jikmunn Next Auth - Dashboard</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero min-h-screen">
        <div className="hero-content text-center">
          <div className="max-w-md">
            <h1 className="text-2xl font-bold">
              Protected route for verified accout
            </h1>
          </div>
        </div>
      </div>
    </>
  );
};

export default Dashboard;
