import React from 'react';
// internal imports
import Head from 'next/head';
import SignIn from '@/components/Auth/SignIn/SignIn';

const Page = () => {
  return (
    <>
      <Head>
        <title>Jikmunn Next Auth - Sign In</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignIn />
    </>
  );
};

export default Page;
