import React from 'react';

// internal imports
import Head from 'next/head';
import HomePage from '@/components/Home/Home';

// external import
import { getSession } from 'next-auth/react';

const Home = () => {
  return (
    <>
      <Head>
        <title>Jikmunn Next Auth</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
};

export default Home;
