import React from 'react';

// internal imports
import Head from 'next/head';
import Dashboard from '@/components/Dashboard/Dashboard';

// external imports
// import { getServerSession } from 'next-auth';
// import { authOptions } from '@/pages/api/auth/[...nextauth]';

const Page = async () => {
  return (
    <>
      <Head>
        <title>Jikmunn Next Auth - Dashboard</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
};

export default Page;
