import Dashboard from '@/components/Dashboard/Dashboard';
// import { authOptions } from '@/pages/api/auth/[...nextauth]';
// import { getServerSession } from 'next-auth';
import Head from 'next/head';
import React from 'react';

const Page = async () => {
  // const session = await getServerSession(authOptions);
  return (
    <>
      {' '}
      <Head>
        <title>Jikmunn Next Auth - Dashboard</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
};

export default Page;
